language: cpp
dist: trusty
compiler:
  - clang
project:
  name: "cpprobotparser"
  description: "Build submitted via Travis CI"
notification_email: apugachevdev@gmail.com
build_command_prepend: "mkdir build ; cd build ; cmake .. ; cd .."
build_command: "make -C build"
env:
  - COMPILER=clang++-3.6