#pragma once

// cpprobotparser_EXPORTS generated by cmake

#ifdef cpprobotparser_EXPORTS
#define CPPROBOTPARSER_EXPORT __declspec(dllexport)
#else
#define CPPROBOTPARSER_EXPORT __declspec(dllimport)
#endif