#pragma once

// cpprobotparser_EXPORTS generated by cmake


#if defined(cpprobotparser_STATIC) || !defined(cpprobotparser_EXPORTS) && !defined(cpprobotparser_STATIC)
    #define CPPROBOTPARSER_EXPORT
#else
    #ifdef cpprobotparser_EXPORTS
        #define CPPROBOTPARSER_EXPORT __declspec(dllexport)
    #else
        #define CPPROBOTPARSER_EXPORT __declspec(dllimport)
    #endif
#endif